# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/viv/lab7_2/lab7_2.srcs/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/mb_block_hdmi_text_controller_0_0.xci
# IP: The module: 'mb_block_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/hdmi_tx_ip/hdmi_tx_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_ip || ORIG_REF_NAME==hdmi_tx_ip} -quiet] -quiet

# IP: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/clk_wiz_ip/clk_wiz_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] -quiet

# IP: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/VRAMBlockMemory/VRAMBlockMemory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VRAMBlockMemory || ORIG_REF_NAME==VRAMBlockMemory} -quiet] -quiet

# XDC: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/clk_wiz_ip/clk_wiz_ip.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/clk_wiz_ip/clk_wiz_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/clk_wiz_ip/clk_wiz_ip_ooc.xdc

# XDC: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/VRAMBlockMemory/VRAMBlockMemory_ooc.xdc

# IP: D:/viv/lab7_2/lab7_2.srcs/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/mb_block_hdmi_text_controller_0_0.xci
# IP: The module: 'mb_block_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/hdmi_tx_ip/hdmi_tx_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_ip || ORIG_REF_NAME==hdmi_tx_ip} -quiet] -quiet

# IP: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/clk_wiz_ip/clk_wiz_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] -quiet

# IP: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/VRAMBlockMemory/VRAMBlockMemory.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VRAMBlockMemory || ORIG_REF_NAME==VRAMBlockMemory} -quiet] -quiet

# XDC: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/clk_wiz_ip/clk_wiz_ip.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/clk_wiz_ip/clk_wiz_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/clk_wiz_ip/clk_wiz_ip_ooc.xdc

# XDC: d:/viv/lab7_2/lab7_2.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/VRAMBlockMemory/VRAMBlockMemory_ooc.xdc
