create_clock -period 10.000 -name clk_100 -waveform {0.000 5.000} [get_ports clk_100MHz]

set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS25 [get_ports reset_rtl_0]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN N15 [get_ports clk_100MHz]
set_property PACKAGE_PIN J2 [get_ports reset_rtl_0]
set_property PACKAGE_PIN B16 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN A16 [get_ports uart_rtl_0_txd]

#play/pause

set_property IOSTANDARD LVCMOS25 [get_ports play_switch]
set_property PACKAGE_PIN G1 [get_ports play_switch]

#loop_enable
set_property IOSTANDARD LVCMOS25 [get_ports loop_enable]
set_property PACKAGE_PIN F2 [get_ports loop_enable]

#usb
set_property IOSTANDARD LVCMOS33 [get_ports gpio_usb_int_tri_i]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_sclk]
set_property PACKAGE_PIN T13 [get_ports gpio_usb_int_tri_i]
set_property PACKAGE_PIN V14 [get_ports usb_spi_sclk]
set_property PACKAGE_PIN V15 [get_ports usb_spi_mosi]
set_property PACKAGE_PIN U12 [get_ports usb_spi_miso]


set_property IOSTANDARD LVCMOS33 [get_ports gpio_usb_rst_tri_o]
set_property PACKAGE_PIN V13 [get_ports gpio_usb_rst_tri_o]
set_property PACKAGE_PIN T12 [get_ports usb_spi_ss]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_ss]


#HDMI Signals
set_property -dict { PACKAGE_PIN V17   IOSTANDARD TMDS_33 } [get_ports {hdmi_tmds_clk_n}]
set_property -dict { PACKAGE_PIN U16   IOSTANDARD TMDS_33 } [get_ports {hdmi_tmds_clk_p}]

set_property -dict { PACKAGE_PIN U18   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_n[0]}]
set_property -dict { PACKAGE_PIN R17   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_n[1]}]
set_property -dict { PACKAGE_PIN T14   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_n[2]}]
                                    
set_property -dict { PACKAGE_PIN U17   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_p[0]}]
set_property -dict { PACKAGE_PIN R16   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_p[1]}]
set_property -dict { PACKAGE_PIN R14   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_p[2]}]

# DAC Signals
set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33  } [get_ports {output_stream}]
set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33  } [get_ports {bit_clk_out}]
set_property -dict { PACKAGE_PIN K16   IOSTANDARD LVCMOS33  } [get_ports {LR_select}]

# HEX
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid_a_0[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid_a_0[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid_a_0[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid_a_0[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid_b_0[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid_b_0[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid_b_0[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid_b_0[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_a_0[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_a_0[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_a_0[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_a_0[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_a_0[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_a_0[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_a_0[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_a_0[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_b_0[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_b_0[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_b_0[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_b_0[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_b_0[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_b_0[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_b_0[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_b_0[0]}]
set_property PACKAGE_PIN G6 [get_ports {hex_grid_a_0[0]}]
set_property PACKAGE_PIN H6 [get_ports {hex_grid_a_0[1]}]
set_property PACKAGE_PIN C3 [get_ports {hex_grid_a_0[2]}]
set_property PACKAGE_PIN B3 [get_ports {hex_grid_a_0[3]}]
set_property PACKAGE_PIN E6 [get_ports {hex_seg_a_0[0]}]
set_property PACKAGE_PIN B4 [get_ports {hex_seg_a_0[1]}]
set_property PACKAGE_PIN D5 [get_ports {hex_seg_a_0[2]}]
set_property PACKAGE_PIN C5 [get_ports {hex_seg_a_0[3]}]
set_property PACKAGE_PIN D7 [get_ports {hex_seg_a_0[4]}]
set_property PACKAGE_PIN D6 [get_ports {hex_seg_a_0[5]}]
set_property PACKAGE_PIN C4 [get_ports {hex_seg_a_0[6]}]
set_property PACKAGE_PIN B5 [get_ports {hex_seg_a_0[7]}]
set_property PACKAGE_PIN F3 [get_ports {hex_seg_b_0[0]}]
set_property PACKAGE_PIN G5 [get_ports {hex_seg_b_0[1]}]
set_property PACKAGE_PIN J3 [get_ports {hex_seg_b_0[2]}]
set_property PACKAGE_PIN H4 [get_ports {hex_seg_b_0[3]}]
set_property PACKAGE_PIN F4 [get_ports {hex_seg_b_0[4]}]
set_property PACKAGE_PIN H3 [get_ports {hex_seg_b_0[5]}]
set_property PACKAGE_PIN E5 [get_ports {hex_seg_b_0[6]}]
set_property PACKAGE_PIN J4 [get_ports {hex_seg_b_0[7]}]
set_property PACKAGE_PIN E4 [get_ports {hex_grid_b_0[0]}]
set_property PACKAGE_PIN E3 [get_ports {hex_grid_b_0[1]}]
set_property PACKAGE_PIN F5 [get_ports {hex_grid_b_0[2]}]
set_property PACKAGE_PIN H5 [get_ports {hex_grid_b_0[3]}]
